### ISSUE TITLE
Fix Github actions issue

### ISSUE THREAD

**Issue by abdirihaman-debugz** [abdirihaman-debugz/messi-games-notify#1]
```
Traceback (most recent call last):
  File "/home/runner/work/messi-games-notify/messi-games-notify/messiGamesNotify.py", line 67, in <module>
    server.sendmail(USER_EMAIL, USER_EMAIL, dataTable)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/smtplib.py", line 878, in sendmail
    esmtp_opts.append("size=%d" % len(msg))
                                  ^^^^^^^^
TypeError: object of type 'PrettyTable' has no len()
```

**Comment by abdirihaman-debugz** [comment]
issue is resolved and the email part works
